name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        variant: [devcontainer, wsl, gnome]
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
        include:
          - variant: devcontainer
            os: alpine
          - variant: devcontainer
            os: debian
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          scripts/test.sh --variant "${{ matrix.variant }}" --os "${{ matrix.os }}"
  verdict:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "All tests passed!"

  notify:
    needs: [test]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - uses: lacherogwu/failed-jobs-discord-notification-action@v1
        with:
          discord_webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          needs_json: ${{ toJSON(needs) }}
          color: 0x0099ff
          username: GitHub Actions
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
